import {
  AccountsPage,
  AdminPage,
  AlertsPage,
  AnalyticsPage,
  AuditLogsPage,
  CaseDetailPage,
  CategoriesPage,
  DashboardPage,
  LandingPage,
  LoginScreen,
  PulseFeedPage,
  ReportsPage,
  SignupScreen,
  SitesPage,
  SubmitFeedbackPage,
  UsersPage,
} from "@/pages/CommandScreens";

export const commandRoutes = [
  { label: "Landing Page", path: "/", element: <LandingPage /> },
  { label: "Login Screen", path: "/login", element: <LoginScreen /> },
  { label: "Sign Up Screen", path: "/signup", element: <SignupScreen /> },
  { label: "Feedback Submission Page", path: "/submit-feedback", element: <SubmitFeedbackPage /> },
  { label: "Main Executive Dashboard", path: "/dashboard", element: <DashboardPage /> },
  { label: "Pulse Feed / Feedback Inbox", path: "/pulse-feed", element: <PulseFeedPage /> },
  { label: "Feedback Detail / Case Management", path: "/case/:id", element: <CaseDetailPage /> },
  { label: "Analytics Overview", path: "/analytics", element: <AnalyticsPage /> },
  { label: "Site Performance Dashboard", path: "/sites", element: <SitesPage /> },
  { label: "Account Performance Dashboard", path: "/accounts", element: <AccountsPage /> },
  { label: "Category Performance Dashboard", path: "/categories", element: <CategoriesPage /> },
  { label: "Alerts & Escalation Center", path: "/alerts", element: <AlertsPage /> },
  { label: "Reporting Center", path: "/reports", element: <ReportsPage /> },
  { label: "Admin Settings", path: "/admin", element: <AdminPage /> },
  { label: "User Management / Role Access", path: "/users", element: <UsersPage /> },
  { label: "System Audit / Activity Logs", path: "/audit-logs", element: <AuditLogsPage /> },
] as const;
